apiVersion: v1
kind: Service
metadata:
  name: hello-neuvector
  namespace: hello-neuvector
spec:
  type: NodePort
  selector:
    app: hello-neuvector
  ports:
    - name: web
      port: 80
      targetPort: web
      nodePort: 30000
